motor_id: 
    [1, 2, 3, 4, 5, 6,
     1, 2, 3, 4, 5, 6,
     1, 2, 3, 4, 5,
     1, 2, 3, 4]
motor_interface_type: "can"
motor_interface: ["can0", "can1", "can2", "can3"]
motor_num: [6, 6, 5, 4]
motor_type: "DM"
motor_model: 
    [2, 2, 1, 1, 1, 1,
     2, 2, 1, 1, 1, 1,
     0, 0, 0, 0, 0,
     0, 0, 0, 0]
master_id_offset: 16
motor_zero_offset: 
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0]
