inference_node:
    ros__parameters:
        model_names: ["policy.onnx", "policy_wave.onnx", "policy_dance.onnx", "policy_punch.onnx"]
        motion_names: ["", "wave.npz", "dance.npz", "punch.npz"]
        obs_layouts:
          - "ang_vel:3, gravity_b:3, cmd_vel:3, dof_pos:21, dof_vel:21, last_action:21"
          - "motion_pos:21, motion_vel:21, ang_vel:3, gravity_b:3, dof_pos:21, dof_vel:21, last_action:21"
          - "motion_pos:21, motion_vel:21, ang_vel:3, gravity_b:3, dof_pos:21, dof_vel:21, last_action:21"
          - "motion_pos:21, motion_vel:21, ang_vel:3, gravity_b:3, dof_pos:21, dof_vel:21, last_action:21"
        frame_stacks: [10, 1, 1, 1]
        obs_stack_orders: ["frame_major", "frame_major", "frame_major", "frame_major"]
        act_alpha: 1.0
        joint_num: 21
        decimation: 5
        intra_threads: 1
        dt: 0.004
        obs_scales_lin_vel: 1.0
        obs_scales_ang_vel: 1.0
        obs_scales_dof_pos: 1.0
        obs_scales_dof_vel: 1.0
        obs_scales_gravity_b: 1.0
        clip_observations: 100.0
        action_scale: 0.25
        clip_actions: 100.0
        usd2urdf: [0, 6, 12, 1, 7, 13, 17, 2, 8, 14, 18, 3, 9, 15, 19, 4, 10, 16, 20, 5, 11]
        clip_cmd: 
            [-0.4, 0.6,
             -0.4, 0.4,
             -0.8, 0.8]
        joint_default_angle:
            [0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0,
             -0.14782176911830902, 0.39768826961517334, 0.04596780240535736, -0.012397955171763897,
             -0.032616160809993744, -0.5540932416915894, 0.00667582219466567, -0.09136339277029037]
        joint_limits:
            [-1.0, 0.6,
             -0.6, 1.0,
             -1.57, 1.57,
             -0.2, 2.5,
             -0.6, 0.6,
             -0.5, 0.5,
             -0.6, 1.0,
             -1.0, 0.6,
             -1.57, 1.57,
             -0.2, 2.5,
             -0.6, 0.6,
             -0.5, 0.5,
             -3.14, 3.14,
             -3.14, 1.57,
             -0.25, 3.14,
             -1.57, 1.57,
             -0.6, 1.57,
             -3.14, 1.57,
             -3.14, 0.25,
             -1.57, 1.57,
             -0.6, 1.57]
        gravity_z_upper: 1.0
